spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    open-in-view: false
  devtools.livereload.enabled: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

backend:
  base-api-url: 'http://localhost:8081'

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081