CREATE SEQUENCE hibernate_sequence INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE TABLE USERS(
    ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    BLOCKED BOOLEAN NOT NULL,
    EMAIL VARCHAR(127),
    EMAIL_VERIFIED BOOLEAN NOT NULL,
    FIRST_NAME VARCHAR(60),
    LAST_NAME VARCHAR(60),
    PASSWORD VARCHAR(255),
    PHONE VARCHAR(17),
    PHONE_VERIFIED BOOLEAN NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (EMAIL),
    UNIQUE (PHONE)
);