ALTER TABLE USERS ADD COLUMN REFERRAL_CODE CHARACTER VARYING(12);
-- Placeholder values for now. To be manually replaced with actual referral codes.
UPDATE USERS SET REFERRAL_CODE = CAST(id AS TEXT);
ALTER TABLE USERS ALTER COLUMN REFERRAL_CODE SET NOT NULL;
ALTER TABLE USERS ADD UNIQUE (REFERRAL_CODE);
